"""add_price_and_dates

Revision ID: f43bd26e2ca8
Revises: dbde6b58424b
Create Date: 2026-01-29 10:32:37.189145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f43bd26e2ca8'
down_revision: Union[str, Sequence[str], None] = 'dbde6b58424b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('books', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('books', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('books', sa.Column('update_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'update_at')
    op.drop_column('books', 'created_at')
    op.drop_column('books', 'description')
    op.drop_column('books', 'price')
    # ### end Alembic commands ###
