global:
  scrape_interval: 15s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels:
          service: 'ticket-api'