"""add waiting-room window columns to events

Revision ID: 7dc383f92999
Revises: 76167cb2eb6f
Create Date: 2026-07-13 15:00:06.237295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dc383f92999'
down_revision: Union[str, Sequence[str], None] = '76167cb2eb6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('queue_opens_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('queue_closes_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'queue_closes_at')
    op.drop_column('events', 'queue_opens_at')
    # ### end Alembic commands ###
