"""add absolute_expires_at

Revision ID: a248c0739bb0
Revises: 9d730a6eb4eb
Create Date: 2026-05-20 16:57:24.764873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a248c0739bb0'
down_revision: Union[str, Sequence[str], None] = '9d730a6eb4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'absolute_expires_at')
    # ### end Alembic commands ###
