"""use SAEnum for status columns

Revision ID: b9a4fce2cc69
Revises: 5729d7399ebd
Create Date: 2026-06-01 09:41:37.745718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a4fce2cc69'
down_revision: Union[str, Sequence[str], None] = '5729d7399ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('DRAFT', 'PUBLISHED', 'CANCELLED', name='eventstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'PAID', 'CONFIRMED', 'EXPIRED', 'CANCELLED', name='orderstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('PENDING', 'PAID', 'CONFIRMED', 'EXPIRED', 'CANCELLED', name='orderstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('events', 'status',
               existing_type=sa.Enum('DRAFT', 'PUBLISHED', 'CANCELLED', name='eventstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
