"""add buyer_info table

Revision ID: cb306b9096a7
Revises: b9a4fce2cc69
Create Date: 2026-06-02 17:03:02.187724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb306b9096a7'
down_revision: Union[str, Sequence[str], None] = 'b9a4fce2cc69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('real_name', sa.String(length=64), nullable=False),
    sa.Column('national_id_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('national_id_dek_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('national_id_lookup_hash', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_buyer_info_national_id_lookup_hash'), 'buyer_info', ['national_id_lookup_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buyer_info_national_id_lookup_hash'), table_name='buyer_info')
    op.drop_table('buyer_info')
    # ### end Alembic commands ###
